SHELL := /bin/bash
LOCALPATH := $(CURDIR)/$(PROJECT)
PYTHONPATH := $(LOCALPATH)/


help:
	@echo "    executa"
	@echo "    Processa o arquivo arquivosaida no diretorio corrente."
	
all: 	executa

compila:	
	python t1-main.py
	
executa:
	 Rscript Programa.R

clear:
	rm -Rf arquivosaida